name: Universe
version: ${version}
main: gg.scala.universe.minecraft.modern.UniversePlugin
api-version: '1.21'
author: Scala Universe
permissions:
  universe.command:
    default: true
    description: Access to the /universe command
  universe.command.status:
    default: true
    description: Check Universe connection status
  universe.command.info:
    default: op
    description: View detailed instance info
  universe.command.players:
    default: op
    description: View online players
  universe.command.tps:
    default: op
    description: View server TPS
