/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns basic status information about the Universe node.
         */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current node information
         * @description Returns system statistics and uptime for the current node.
         */
        get: operations["getNode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current node configuration
         * @description Returns the current node's main configuration ( UniverseMainConfiguration).
         */
        get: operations["getNodeConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reload node configuration
         * @description Reloads the node configuration from disk. (Not fully implemented.)
         */
        post: operations["reloadNodeConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cluster/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all cluster nodes
         * @description Returns a list of all nodes in the Hazelcast cluster.
         */
        get: operations["listNodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cluster/nodes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a specific node
         * @description Returns detailed information about a cluster node, including its instances.
         */
        get: operations["getNodeById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cluster/nodes/{id}/command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute a command on a node
         * @description Executes a console command on the specified node.
         *     - If `id` is the current node: use `/api/commands/execute` instead
         *     - If `id` is a remote node: dispatches via Hazelcast (not yet implemented)
         */
        post: operations["executeNodeCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all instances
         * @description Returns all instances across the cluster (active and stopped).
         */
        get: operations["listInstances"];
        put?: never;
        /**
         * Create a new instance
         * @description Deploys a new instance using the specified configuration.
         */
        post: operations["createInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get instance details
         * @description Returns detailed information about an instance.
         *
         *     **Public Access**: This endpoint is accessible with PUBLIC permission keys.
         */
        get: operations["getInstance"];
        put?: never;
        post?: never;
        /**
         * Stop and delete an instance
         * @description Stops the instance and removes it from the cluster.
         */
        delete: operations["deleteInstance"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get instance logs
         * @description Returns the most recent log lines for an instance.
         *
         *     **Public Access**: This endpoint is accessible with PUBLIC permission keys.
         */
        get: operations["getInstanceLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{id}/live-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live log stream (WebSocket)
         * @description Opens a WebSocket connection that streams live log output from the instance.
         *
         *     **Public Access**: This endpoint is accessible with PUBLIC permission keys.
         *
         *     Connect with:
         *     ```
         *     ws://host/api/instances/{id}/live-log
         *     Authorization: Bearer YOUR_TOKEN
         *     ```
         *
         *     Messages are sent as text frames.
         */
        get: operations["liveLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update instance state
         * @description Updates the state and/or heartbeat timestamp of an instance.
         */
        put: operations["updateInstanceState"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{id}/lifecycle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change instance lifecycle
         * @description Controls the lifecycle of an instance:
         *     - `start` — Start a stopped instance
         *     - `stop` — Stop a running instance
         *     - `restart` — Restart the instance
         */
        patch: operations["patchInstanceLifecycle"];
        trace?: never;
    };
    "/instances/{id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute a command on an instance
         * @description Sends a command to the instance's stdin. The command is piped directly
         *     to the running process (e.g., Minecraft console).
         */
        post: operations["executeInstanceCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/configurations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all configurations
         * @description Returns all instance configurations.
         */
        get: operations["listConfigurations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/configurations/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a configuration
         * @description Returns a specific configuration by name.
         */
        get: operations["getConfiguration"];
        /**
         * Create or update a configuration
         * @description Creates or updates an instance configuration.
         */
        put: operations["putConfiguration"];
        post?: never;
        /**
         * Delete a configuration
         * @description Deletes an instance configuration.
         */
        delete: operations["deleteConfiguration"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all templates
         * @description Returns all available templates organized by group.
         */
        get: operations["listTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{group}/{name}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export template as zip
         * @description Downloads the template directory as a zip archive for cross-node import.
         */
        get: operations["exportTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{group}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get template details
         * @description Returns details about a specific template.
         */
        get: operations["getTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync templates across cluster
         * @description Dispatches a template sync task to the cluster via Hazelcast.
         */
        post: operations["syncTemplates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/variables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List template variables
         * @description Returns placeholder variables available for template file editing.
         */
        get: operations["listTemplateVariables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import template from zip
         * @description Multipart upload (group, name, file) extracting a zip into ./templates/
         */
        post: operations["importTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{group}/{name}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List template files */
        get: operations["listTemplateFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{group}/{name}/files/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read template file */
        get: operations["readTemplateFile"];
        /** Write template file */
        put: operations["writeTemplateFile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/commands/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute a console command
         * @description Executes a command on the Universe master node's console.
         *     The command output is captured and returned in the response.
         */
        post: operations["executeCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/console": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Interactive console (WebSocket)
         * @description Opens an interactive WebSocket console to the Universe master node.
         *
         *     Connect with:
         *     ```
         *     ws://host/api/console
         *     Authorization: Bearer YOUR_TOKEN
         *     ```
         *
         *     Send commands as text frames. Responses are streamed back as text frames.
         */
        get: operations["console"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extensions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List installed extensions
         * @description Returns all discovered Universe extensions with load status.
         */
        get: operations["listExtensions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics scrape endpoint
         * @description Returns metrics in Prometheus exposition format.
         *     Used by Prometheus or other monitoring systems.
         */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        InstanceInfo: {
            /**
             * @description Unique 6-character instance ID
             * @example a1b2c3
             */
            id?: string;
            /**
             * @description Name of the configuration this instance uses
             * @example lobby
             */
            configurationName?: string;
            /**
             * @description ID of the node hosting this instance
             * @example node-1
             */
            wrapperNodeId?: string;
            /**
             * @description Host address clients should connect to
             * @example 127.0.0.1
             */
            hostAddress?: string;
            /**
             * @description Port allocated for this instance
             * @example 25565
             */
            allocatedPort?: number;
            state?: components["schemas"]["InstanceState"];
            /**
             * Format: int64
             * @description Unix timestamp of last heartbeat
             */
            lastHeartbeat?: number;
            /**
             * Format: int64
             * @description Process ID (null for container runtimes)
             */
            processPid?: number | null;
            /**
             * @description Allocated RAM in MB
             * @example 2048
             */
            allocatedRamMB?: number;
            /**
             * @description Allocated CPU units (100 = 1 core)
             * @example 100
             */
            allocatedCpu?: number;
            /**
             * @description Runtime provider used (screen, docker, k8s, etc.)
             * @example docker
             */
            runtime?: string;
        };
        /**
         * @description - **CREATING** — Instance is being deployed
         *     - **ONLINE** — Instance is running and healthy
         *     - **OFFLINE** — Instance has missed heartbeats
         *     - **STOPPED** — Instance has been stopped
         * @enum {string}
         */
        InstanceState: "CREATING" | "ONLINE" | "OFFLINE" | "STOPPED";
        Configuration: {
            /**
             * @description Unique configuration name
             * @example lobby
             */
            name?: string;
            /**
             * @description Runtime provider key
             * @default screen
             * @example docker
             */
            runtime: string;
            /**
             * @description Command to start the instance
             * @example java -Xmx2048M -jar server.jar
             */
            command?: string;
            /**
             * @description Whether this is a static (persistent) instance
             * @default false
             */
            static: boolean;
            /**
             * @description RAM allocated in MB
             * @default 2048
             * @example 2048
             */
            ramMB: number;
            /**
             * @description CPU units (100 = 1 core)
             * @default 100
             * @example 100
             */
            cpu: number;
            /**
             * @description Groups this configuration belongs to
             * @example [
             *       "lobby"
             *     ]
             */
            instanceGroups?: string[];
            /**
             * @description Nodes allowed to host this instance
             * @example [
             *       "node-1"
             *     ]
             */
            nodes?: string[];
            /**
             * @description Host address for client connections
             * @example 127.0.0.1
             */
            hostAddress?: string;
            availablePorts?: components["schemas"]["PortRange"];
            /**
             * @description Minimum number of instances to maintain
             * @default 1
             * @example 1
             */
            minimumServiceCount: number;
            /**
             * @description Environment variables for the instance
             * @example {
             *       "UNIVERSE_INSTANCE_ID": "%INSTANCE_ID%"
             *     }
             */
            environmentVariables?: {
                [key: string]: string;
            };
            templateInstallationConfig?: components["schemas"]["TemplateInstallationConfig"];
            /**
             * @description Files to modify after template installation
             * @example [
             *       "server.properties"
             *     ]
             */
            fileModifications?: string[];
            /** @description Additional configuration properties */
            properties?: {
                [key: string]: string;
            };
        };
        PortRange: {
            /**
             * @description Minimum port number
             * @example 25565
             */
            min?: number;
            /**
             * @description Maximum port number
             * @example 25570
             */
            max?: number;
        };
        TemplateInstallationConfig: {
            /** @description Templates to install (all required) */
            allOf?: components["schemas"]["Template"][];
            /** @description Template groups to install entirely */
            allInGroups?: string[];
            /** @description Templates to choose one from */
            oneOf?: components["schemas"]["Template"][];
            /** @description Template groups to choose one template from */
            oneInGroups?: string[];
            /**
             * @description Whether templates override existing files
             * @default false
             */
            onTemplatePasteOverridePresentFiles: boolean;
        };
        Template: {
            /** @example server */
            name?: string;
            /** @example default */
            group?: string;
            /**
             * @description Storage backend (local, s3)
             * @example local
             */
            storage?: string;
            /**
             * @description Installation priority order
             * @example 1
             */
            priority?: number;
        };
        NodeResources: {
            /** @description Currently used RAM in MB */
            usedRamMB?: number;
            /** @description Currently used CPU units */
            usedCpu?: number;
        };
        UniverseMainConfiguration: {
            /** @example 127.0.0.1 */
            address?: string;
            /**
             * @description Hazelcast cluster port
             * @example 6000
             */
            port?: number;
            /**
             * @description REST API port
             * @example 7000
             */
            apiPort?: number;
            /** @example node-1 */
            nodeId?: string;
            /** @example universe-cluster */
            clusterName?: string;
            isMasterNode?: boolean;
            masterAddress?: string;
            masterPort?: number;
            masterApiPort?: number;
            debug?: boolean;
            maxRamMB?: number;
            maxCpu?: number;
        };
        CreateInstanceRequest: {
            /**
             * @description Name of the configuration to use
             * @example lobby
             */
            configurationName: string;
        };
        UpdateStateRequest: {
            /**
             * @description New state value
             * @enum {string}
             */
            state: "CREATING" | "ONLINE" | "OFFLINE" | "STOPPED";
            /**
             * Format: int64
             * @description Unix timestamp (optional, resets if not provided)
             */
            lastHeartbeat?: number;
        };
        ExecuteOnInstanceRequest: {
            /**
             * @description Command to execute on the instance
             * @example op andyreckt
             */
            command: string;
        };
        ClusterCommandRequest: {
            /**
             * @description Console command to execute
             * @example instance list
             */
            command: string;
        };
        TemplateSyncRequest: {
            /**
             * @description Template pattern to sync (e.g., default/*, group/name)
             * @example default/*
             */
            pattern: string;
        };
        ExecuteCommandRequest: {
            /**
             * @description Console command to execute on the master node
             * @example help
             */
            command: string;
        };
        ExtensionInfo: {
            /**
             * @description Extension identifier
             * @example runtime-docker
             */
            id: string;
            /** @example 1.0.0 */
            version: string;
            /**
             * @description LOADED if active, SKIPPED if master-only on a wrapper node
             * @enum {string}
             */
            status: "LOADED" | "INSTALLED" | "SKIPPED";
            masterOnly: boolean;
            reloadable: boolean;
        };
    };
    responses: {
        /** @description Missing or invalid Authorization header */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Unauthorized */
                    error?: string;
                };
            };
        };
        /** @description Rate limit exceeded */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Rate limit exceeded. Retry after 45000ms. */
                    error?: string;
                    /** @example 45000 */
                    retryAfterMs?: number;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Universe is running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /** @example node-1 */
                        nodeId?: string;
                        /** @example universe-cluster */
                        clusterName?: string;
                        /** @example true */
                        master?: boolean;
                    };
                };
            };
        };
    };
    getNode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        clusterName?: string;
                        version?: string;
                        master?: boolean;
                        address?: string;
                        port?: number;
                        apiPort?: number;
                        /** Format: int64 */
                        uptimeMs?: number;
                        system?: {
                            availableProcessors?: number;
                            systemLoadAverage?: number;
                            /** Format: int64 */
                            freeMemory?: number;
                            /** Format: int64 */
                            totalMemory?: number;
                            /** Format: int64 */
                            maxMemory?: number;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getNodeConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseMainConfiguration"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    reloadNodeConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            401: components["responses"]["Unauthorized"];
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Not Implemented */
                        error?: string;
                    };
                };
            };
        };
    };
    listNodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of nodes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Hazelcast member UUID */
                        id?: string;
                        /** @description Human-readable node name */
                        name?: string;
                        address?: string;
                        port?: number;
                        /** @description Whether this is the current node */
                        local?: boolean;
                        resources?: components["schemas"]["NodeResources"];
                    }[];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getNodeById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        name?: string;
                        address?: string;
                        port?: number;
                        local?: boolean;
                        /** @description Instance IDs hosted on this node */
                        instances?: string[];
                        resources?: components["schemas"]["NodeResources"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    executeNodeCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClusterCommandRequest"];
            };
        };
        responses: {
            /** @description Cannot execute command on local node via API */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Use /api/commands/execute for local node */
                        error?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Remote node command execution not yet implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listInstances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of instances */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceInfo"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInstanceRequest"];
            };
        };
        responses: {
            /** @description Instance created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceInfo"];
                };
            };
            /** @description Invalid configuration name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceInfo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    deleteInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance stopped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Instance stopped */
                        message?: string;
                        instanceId?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getInstanceLogs: {
        parameters: {
            query?: {
                /** @description Number of log lines to return */
                lines?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Log lines */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        lines?: string[];
                        totalLines?: number;
                        instanceId?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    liveLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebSocket connection established */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    updateInstanceState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStateRequest"];
            };
        };
        responses: {
            /** @description State updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceInfo"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    patchInstanceLifecycle: {
        parameters: {
            query: {
                /** @description Target lifecycle state */
                target: "start" | "stop" | "restart";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lifecycle changed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                        instanceId?: string;
                        target?: string;
                    };
                };
            };
            /** @description Invalid target state or instance not found */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    executeInstanceCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteOnInstanceRequest"];
            };
        };
        responses: {
            /** @description Command dispatched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Command dispatched */
                        message?: string;
                        instanceId?: string;
                        command?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listConfigurations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of configurations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Configuration"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuration details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Configuration"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Configuration not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    putConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Configuration"];
            };
        };
        responses: {
            /** @description Configuration saved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuration deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of templates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        group?: string;
                        templates?: components["schemas"]["Template"][];
                    }[];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    exportTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Zip archive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Template not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Template details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        group?: string;
                        name?: string;
                        path?: string;
                        exists?: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    syncTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateSyncRequest"];
            };
        };
        responses: {
            /** @description Sync initiated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Template sync dispatched */
                        message?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listTemplateVariables: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Variable list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        variables?: {
                            key?: string;
                            description?: string;
                        }[];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    importTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    group?: string;
                    name?: string;
                    overwrite?: boolean;
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description Import successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listTemplateFiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File listing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    readTemplateFile: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                group: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    writeTemplateFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    path: string;
                    content: string;
                };
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    executeCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteCommandRequest"];
            };
        };
        responses: {
            /** @description Command output */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        command?: string;
                        output?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    console: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebSocket connection established */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listExtensions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of extensions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionInfo"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example # HELP universe_instances_total Total number of instances
                     *     # TYPE universe_instances_total gauge
                     *     universe_instances_total 5
                     */
                    "text/plain": string;
                };
            };
        };
    };
}
